### PR TITLE
Changes from our SA

### LINKED ISSUE #49: Add categories to module selector
At the moment it is hard to add new Modules, as you don't know which category they belong to. 
I would like to propose that the select component gets updated to be able filter by category, and maybe show some more information on the module.

### LINKED ISSUE #66: Adding modules on iOS is broken
I only observed this with iOS 17.4.1 and I think it is a bug.

Reported by others [here](https://forums.developer.apple.com/forums/thread/750542) and [here](https://twitter.com/webtonull/status/1779803326080532804).

### PR DESCRIPTION
**Pull request by StefanieJaeger**
This PR contains all changes made during our SA as well as some smaller bug fixes made later on.
I would recommend to first merge this [PR](https://github.com/lost-university/data/pull/18), so we can use the newest tag of the normal data repo, instead of having to reference our fork of the data repo.
Closes #49 and closes #66.

### CODE REVIEW

**Comment by StefanieJaeger** [comment]
Closes issues #49 and #66

File: CNAME
Comment (jeremystucki) [inline CNAME:1]: Please revert this change for the PR, otherwise the site breaks :(

File: src/components/AccreditedModuleBadge.vue [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+      }
+      return classes;
+    },
+    tooltip() {
+      if(this.accreditedModule.validationInfo) {
+        return this.accreditedModule.validationInfo.tooltip;
+      }
+
+      const categoryNames = this.accreditedModule.categoryIds
+        .map(id => store.getters.categories.find(c => c.id === id)?.name)
```
Comment (jeremystucki) [inline src/components/AccreditedModuleBadge.vue:59]: I just realized that we should maybe migrate categories to be an object instead of an array, but not necessarily in this PR.

We often find a category by id, which could be replaced by a simple lookup.

File: src/helpers/validation-helper.ts [hunk 2]
```diff
@@ -0,0 +1,281 @@
...
+      [] as string[]
+    ).join(', ');
+
+    let tooltip = `Modul ist doppelt im Plan, in Semestern ${distinctSemesterNames}`;
+    let text = `${moduleId} ist in mehreren Semestern (${distinctSemesterNames})`;
+    if (predecessorOrSuccessorOccurences.length) {
+      if(predecessorOrSuccessorOccurences.length === occurences.length - 1) {
+        const predecessorOrSuccessorNames = predecessorOrSuccessorOccurences
+          .map(m => m.module.name)
+          .reduce((distinct, name) => distinct.includes(name) ? distinct : [...distinct, name], [] as string[])
```
Comment (jeremystucki) [inline src/helpers/validation-helper.ts:186]: TIL that JS doesn't have a `distinct` operator. :(

File: src/helpers/validation-helper.ts [hunk 3]
```diff
@@ -0,0 +1,281 @@
...
+        missing.push(moduleIdForPosition);
+      }
+    }
+
+    if(missing.length == 0 && later.length == 0) {
+      return null;
+    }
+
+    const tooltipForMissing = missing.length ? `Nicht eingeplante, empfohlene Module: ${missing.join(', ')}` : '';
+    const tooltipForLater = later.length ? `Später eingeplante, empfohelen Module: ${later.join(', ')}` : '';
```
Comment (jeremystucki) [inline src/helpers/validation-helper.ts:242]:
```suggestion
    const tooltipForLater = later.length ? `Später eingeplante, empfohlene Module: ${later.join(', ')}` : '';
```

**Review by jeremystucki — COMMENTED** [review]
Due to the size of this PR I can't give a thorough review. Let's wait a few days to see if someone else want to take a look and otherwise we merge it and see what happens.

Should we add a link to `old.lost.university` in case this breaks something?

**Comment by jeremystucki** [comment]
> Closes issues #49 and #66

GitHub uses [specific syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to close issues automatically. Please adjust the comment accordingly.

File: src/components/AccreditedModuleBadge.vue (hunk 1 above)
Comment (StefanieJaeger) [reply src/components/AccreditedModuleBadge.vue:59]: Sounds smart, feel free to open an issue for that :)

**Comment by jeremystucki** [comment]
Please apply the following two patches.

### Enabling alt text on mobile

```
diff --git a/src/components/Module.vue b/src/components/Module.vue
index 19aabb8..9228a55 100644
--- a/src/components/Module.vue
+++ b/src/components/Module.vue
@@ -8,12 +8,14 @@
       <span
         v-if="module.validationInfo && module.validationInfo.severity === 'soft'"
         :title="module.validationInfo.tooltip"
+        tabindex="0"
       >
         <font-awesome-icon :icon="['fa', 'info-circle']" />
       </span>
       <span
         v-if="module.validationInfo && module.validationInfo.severity === 'hard'"
         :title="module.validationInfo.tooltip"
+        tabindex="0"
       >
         <font-awesome-icon :icon="['fa', 'circle-exclamation']" />
       </span>
diff --git a/style.css b/style.css
index b5c61c9..257c07c 100644
--- a/style.css
+++ b/style.css
@@ -1,3 +1,22 @@
 @tailwind base;
 @tailwind components;
 @tailwind utilities;
+
+@media (hover: none) {
+    [title] {
+        position: relative;
+        display: inline-flex;
+        justify-content: center;
+    }
+    [title]:focus::after {
+        content: attr(title);
+        position: absolute;
+        top: 90%;
+        color: #000;
+        background-color: #fff;
+        border: 1px solid;
+        width: fit-content;
+        padding: 3px;
+        z-index: 99;
+    }
+}
```

### Adding a banner to the footer
```
diff --git a/src/components/PageFooter.vue b/src/components/PageFooter.vue
index 853d6bf..18b6b4a 100644
--- a/src/components/PageFooter.vue
+++ b/src/components/PageFooter.vue
@@ -26,6 +26,16 @@
       />
     </a>
   </footer>
+  <div class="bg-[#8c195f] text-white text-center py-4">
+    <span class="font-bold">
+      Die Webseite wurde kürzlich im Rahmen einer SA überarbeitet und hat jetzt ein paar neue Features
+    </span>
+    <br />
+    <span class="text-sm">
+      Falls etwas nicht funktionieren sollte, eröffne bitte ein Issue <a href="https://github.com/lost-university/web/issues/new/choose"><u>auf GitHub.</u></a>
+      Die vorherige Version ist unter <a href="https://old.lost.university"><u>old.lost.university</u></a> weiterhin für eine begrenzte Zeit verfügbar.
+    </span>
+  </div>
 </template>
 
 <script lang="ts">
```

**Review by jeremystucki — APPROVED** [review]
